### ISSUE TITLE
DataTables Column with Point Coordinate filled server-side - Leaflet

### ISSUE THREAD

**Issue by Snogo** [MattGingery/LeafletExamples#1]
Dear Matt
thank you very much for your Leaflet Examples. I am just starting but I think I can do what I want to do with your examples. I want to show a DataTable which is filled with data filled server-sidedly and if I click on a row it should go to the point on the Leaflet map. one Column in the DataTable has Point coordinates. 
Your examples do this magic jump to the coordinate. however the points and polygons are always drawn manually before or are loaded via GeoJSON and then drawn and are never actually loaded inside the DataTables if I understand it correctly. but how do I display all the coordinates from a point coordinate column in the DataTable?
I hope that is comprehensible
cheers
chris

**Comment by MattGingery** [comment]
Hello Chris,
I just got access back to my GitHub account after switching emails a while ago so sorry I did not respond sooner.
To do what you are asking:

1. Set the variable dataSet to an array of lat/long values, addresses, and whatever other data you want to display.  You can also populate DataTables using an AJAX call, if desired.
2. Change the "columns" value in the searchTable to display these columns as desired.  You will probably want to make the lat/long columns invisible (see columnDefs value).
3. On the $('#searchTable tbody').on('click', 'tr', function() do the following steps:
  a. Get the lat and long data and data to display from the selected row.
  b. Format the data to display as html and place in a new variable: formatPopupHtml.
  c. Call this code to draw the marker: let newMarker = L.marker([lat, lng]).addTo(lfmap).bindPopup(formatPopupHtml); 
  d. Call this code to pop-up the display data: newMarker.openPopup(centerLatLng);


Good luck!
Matt
